added linters & .gitignore
brainskev/Hello-world pull request #3
Opened 2022-06-30 11:56 UTC by brainskev

Requesting for code review

2022-06-30 13:23 UTC, HAMMAS-SALEEM requested changes
# First of all, Welcome to Microverse :bouquet: :bouquet:

# Changes Requested :recycle:

![almost there](https://nairametrics.com/wp-content/uploads/2015/07/Nearly-there.jpg)

## Hey @brainskev :wave: 
### Highlights :1st_place_medal:

Your project is working :clap:
Good commit history :heavy_check_mark:
Following Github Flow :heavy_check_mark:
Following HTML, CSS best practices :heavy_check_mark:
Using .gitignore file :heavy_check_mark:
Meaningful commit messages :heavy_check_mark:
Descriptive PR title :heavy_check_mark: 

You have made a great effort in implementing some changes from the previous reviewer in your project :blush: and I can see that but you need to work on some issues to go to the next project but you are almost there. :+1:

### Your Summary
![re-review-hello-microverse](https://user-images.githubusercontent.com/93039359/176687653-a1416017-3c34-4d08-b4f7-9cd7bcffcb37.png)

### Descriptive Summary Example :heavy_check_mark:
![clinton summary](https://user-images.githubusercontent.com/93039359/176204344-0962abcb-f3b4-4a19-8602-7dea9f09d0f0.png)

### [Optional]

- [ ] You don't have a summary for your project. You can see the image above to get an idea of what a descriptive summary looks like. The summary tells in detail what are you doing in this pull request and why. :thinking:
### Mandatory Change

### Your Linters
![first hello microverse linters](https://user-images.githubusercontent.com/93039359/176688110-24ae34ed-7c09-4eb5-821c-b936a79f7d02.png)

- [ ] Linters are not working please try to fix them. :+1:

### Once you implement all the changes you should be ready to submit your project for a re-review :rocket: :rocket:

Cheers and Happy coding!👏👏👏

### Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification. You can reach out to me on slack by searching my name (Hammas Bin Saleem) for any explanation.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-04 15:46 UTC, prolajumokeoni approved these changes
Kindly see summary below, your pull request message should be descriptive

2022-07-04 15:48 UTC, prolajumokeoni requested changes
[OPTIONAL]

Just as the previous [reviewer requested](https://github.com/brainskev/Hello-world/pull/3#pullrequestreview-1024868225) your pull request message should be descriptive, please edit your pull request a short descriptive message, explaining changes in your pr

2022-07-04 15:57 UTC, prolajumokeoni approved these changes

2022-07-07 08:56 UTC, merged